engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    Naming/ShortMethod:
      minimum: 2
    Naming/ShortVariable:
      minimum: 2
    Controversial/CamelCaseParameterName:
      enabled: false
    Controversial/CamelCaseVariableName:
      enabled: false
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- tests/