sudo: false

language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

before_install:
  - composer selfupdate

install:
  - composer install

script: vendor/bin/codecept run unit

matrix:
  fast_finish: true
  allow_failures:
    - php: 
      - hhvm

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0a9608677dfcf2737773
    on_success: always
    on_failure: always
    on_start: never