language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly
  - hhvm

before_install:
  - composer selfupdate

install:
  - COMPOSER_ROOT_VERSION=dev-master composer install

script: vendor/bin/codecept run unit --coverage --coverage-xml --coverage-html

after_success:
  - vendor/bin/test-reporter

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0a9608677dfcf2737773
    on_success: always
    on_failure: always
    on_start: never

addons:
  code_climate:
    repo_token: 9257045a3d2c1ca68c14ed8352b093b91c1b61f6fee57e37a56541f0c238240f