language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly
  - hhvm

before_install:
  - composer selfupdate

install:
  - composer install

script: vendor/bin/codecept run unit

# Code Climate script depends on setting CODECLIMATE_REPO_TOKEN env var on Travis CI admin
after_script:
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0a9608677dfcf2737773
    on_success: always
    on_failure: always
    on_start: never